### ISSUE TITLE
no such image

### ISSUE THREAD

**Issue by ifelixculpa** [linuxserver/docker-plex#317] opened 2022-06-25 12:51 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Docker logs

hi getting this error while adding plex server to container

![image](https://user-images.githubusercontent.com/13099434/175774223-5c102387-d60d-41dd-bd05-b2179aace30b.png)

**Comment by aptalca** [comment] 2022-06-25 12:54
It's there: https://hub.docker.com/r/linuxserver/plex/tags
Check your network/dns settings and try without portainer.

Closing because it's not a bug

**Closed by aptalca** 2022-06-25 12:54 UTC

**Comment by ifelixculpa** [comment] 2022-06-25 13:19
getting errors

**Comment by ifelixculpa** [comment] 2022-06-25 13:19
> It's there: https://hub.docker.com/r/linuxserver/plex/tags Check your network/dns settings and try without portainer.
> 
> Closing because it's not a bug

still getting errors

**Comment by james-d-elliott** [comment] 2022-06-25 13:29
Seems fine:

```bash
$ docker pull linuxserver/plex:latest
latest: Pulling from linuxserver/plex
a825881b5de5: Pull complete
a9699494e6d8: Pull complete
7ccf87047b90: Pull complete
adb983d372d2: Pull complete
4670158d3d8c: Pull complete
7d018c5b6330: Pull complete
c49175c2bc39: Pull complete
d1c270463e84: Pull complete
64f7fc2b8243: Pull complete
Digest: sha256:67754d5edded36701af18c5ecac02ee6f4a0908b60dfe57913682b80cce87aea
Status: Downloaded newer image for linuxserver/plex:latest
docker.io/linuxserver/plex:latest

$ docker pull docker.io/linuxserver/plex:latest
latest: Pulling from linuxserver/plex
Digest: sha256:67754d5edded36701af18c5ecac02ee6f4a0908b60dfe57913682b80cce87aea
Status: Image is up to date for linuxserver/plex:latest
docker.io/linuxserver/plex:latest
```

**Comment by ifelixculpa** [comment] 2022-06-25 13:44
> 

![image](https://user-images.githubusercontent.com/13099434/175776259-35397ca4-8cd7-416e-a719-481ae099cfec.png)

**Comment by ifelixculpa** [comment] 2022-06-25 13:48
![image](https://user-images.githubusercontent.com/13099434/175776433-7b00a542-35ac-4843-a16f-3800082743f4.png)

**Comment by j0nnymoe** [comment] 2022-06-25 13:57
That indeed is DNS issues on your host.

**Comment by ifelixculpa** [comment] 2022-06-25 14:03
> That indeed is DNS issues on your host.

just tried with different internet and gives same issue

**Comment by j0nnymoe** [comment] 2022-06-25 14:11
Well, something on your host is blocking DNS requests on port 53 (as per the error in portainer), @james-d-elliott has already proven there is no issue with the repo. Again, it's a issue local to your host and not our repo.

You didn't bother providing any information that was requested in the issue template about your setup and we don't have a crystal ball.

**Comment by ifelixculpa** [comment] 2022-06-25 14:16
> Well, something on your host is blocking DNS requests on port 53 (as per the error in portainer), @james-d-elliott has already proven there is no issue with the repo. Again, it's a issue local to your host and not our repo.
> 
> You didn't bother providing any information that was requested in the issue template about your setup and we don't have a crystal ball.

yes sir i am sorry i am going back and fourth about setting things up il re check everything
thanks alot everyone
