### ISSUE TITLE
Plex Media Server is already running. Will not start

### ISSUE THREAD

**Issue by NathanTheGr8** [linuxserver/docker-plex#134] opened 2018-08-18 02:01 UTC
My plex docker container won't start. I have tried restarting my server, restarting container, and deleting and recreating the container. 

Debian 9.5

docker create \
--name=plex \
--restart=always \
--label=com.centurylinklabs.watchtower.enable=true \
--net=host \
-e VERSION=latest \
-e PGID=0 -e PUID=0  \
-e TZ=America/Chicago \
-v /storage/docker/plex:/config \
-v /storage/share:/data/share \
-v /storage/transcode:/transcode \
linuxserver/plex

Logs

Starting Plex Media Server.
Plex Media Server is already running. Will not start...

From inside the container 
root@pve:/data/share# systemctl status plex.servic
Failed to get properties: Launch helper exited with unknown return code 1

Googling a bit I found this https://github.com/waliworld/plex-docker/issues/3, 
but there they just added a 3 second delay to fix it. I don't think that is my problem.

**Comment by NathanTheGr8** [comment] 2018-08-20 21:41
I was just running it as root to see if permissions were the problem. Normally run it as www-data (33). I ended up just nuking the container and data.

**Comment by IAmNBG** [comment] 2018-08-29 01:03
Ever figure it out? I'm also having this issue

**Comment by viruz82** [comment] 2018-09-09 06:37
+1

**Comment by swvajanyatek** [comment] 2018-11-09 15:34
same here

**Comment by j0nnymoe** [comment] 2018-11-09 15:38
`same here` and `+1` isn't helpful. If you are having issues with the container, please post your docker run/compose information and any logs related to it.

**Comment by homerr** [comment] 2018-11-19 15:13
Can we have some more information please or we'll close this issue off. Information on the host environment, storage environment, docker run/compose commands and any other relevant information would help to figure this one out.

**Comment by roobandev** [comment] 2018-12-15 16:34
Met with this issue today,

Looks like plexmediserver.pid file under Library/Application Support/Plex Media Server is causing the plex to start. Deleted the file and it worked fine. Hope this helps.

**Comment by travisghansen** [comment] 2018-12-25 07:15
`rm /config/Library/Application\ Support/Plex\ Media\ Server/plexmediaserver.pid` should probably be a part of the container init process.

**Comment by Amaelh** [comment] 2018-12-26 20:57
Same here with the ARMHF image when my docker instance is not stopped cleanly (e.g. : system power loss). Looks like a clean "docker stop ..." followed by a "docker start ..." resolves this issue ??

Below an extract of my logs, I'm available at any time for more tests to solve this as I encounter this on a regular basis.

```
Daemon already running on PID 248
Daemon already running on PID 248
Daemon already running on PID 248
Daemon already running on PID 248
Daemon already running on PID 248
Daemon already running on PID 248
Daemon already running on PID 248
Daemon already running on PID 248
Daemon already running on PID 248
Daemon already running on PID 248
Daemon already running on PID 248
Daemon already running on PID 248
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-dbus: executing...
[cont-init.d] 30-dbus: exited 0.
[cont-init.d] 40-chown-files: executing...
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
6 3000 /config/Library/Application Support
8192
Daemon already running on PID 243
Process 243 died: No such process; trying to remove PID file. (/run/avahi-daemon//pid)
Found user 'avahi' (UID 103) and group 'avahi' (GID 104).
Successfully dropped root privileges.
avahi-daemon 0.7 starting up.
No service file found in /etc/avahi/services.
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
*** WARNING: Detected another IPv6 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
Joining mDNS multicast group on interface veth5ac59f8.IPv6 with address fe80::4ccf:63f1:42a:77e6.
New relevant interface veth5ac59f8.IPv6 for mDNS.

```

**Comment by IronicBadger** [comment] 2019-02-06 13:54
Closing due to lack of activity.

**Comment by Amaelh** [comment] 2019-02-14 19:30
Well, even if nobody answers the issue is still there. Can you please reopen and check if a developer can take a look at it ? We have several users pointing this out, I'm available for any detailled tests.

**Comment by aptalca** [comment] 2019-02-14 20:57
Your issue was the avahi daemon, which has since been removed from this image.

We'll look into whether it's necessary to clean up plex's pid if container is killed (uncleanly)

**Comment by travisghansen** [comment] 2019-02-14 21:57
@aptalca it is required.  plex won't start if the pid file is laying around.

**Comment by aptalca** [comment] 2019-02-15 16:47
reopening until fixed

**Closed** 2019-02-15 16:59 UTC

**Comment by travisghansen** [comment] 2019-02-15 18:46
I just let a comment on the commit.  You may need to quote the path...

**Comment by thelamer** [comment] 2019-02-15 18:54
You are correct that is my fault , I merged this . Will have a fix shortly

**Comment by aptalca** [comment] 2019-02-15 21:42
yeah, my bad, juggling too many things at work

**Comment by Amaelh** [comment] 2019-02-17 13:21
Thanks :)
