### ISSUE TITLE
is Avahi required when hosted remotely on VPS ?

### ISSUE THREAD

**Issue by thechile** [linuxserver/docker-plex#72] opened 2016-11-01 08:02 UTC
when i start the container i get lots of 'stuff' about `Joining mDNS multicast group on interface...`. Since i have 20 containers i have 20 veth interfaces so i get many lines about mDNS. 

Not the end of the world but since i run these containers on remote VPS i was wondering if running Avahi was even required ? On local network sure, it helps discovery etc.. but when hosted remotely can the container footprint be reduced by having option to disable Avahi  ?

thanks.

**Comment by zaggash** [comment] 2016-11-01 08:43
Hi,

Are you the Scott I know from GNS ?

Since it was designed to work on NAS at the beggining, lets have a talk with the others.
Maybe @sparkyballs have some ideas behind it :)
But I think its mainly linked to the NAS usage

**Comment by thechile** [comment] 2016-11-01 09:37
yup, that Scott, but you have me at a disadvantage good sir :)

**Comment by thechile** [comment] 2016-11-02 02:18
Without modifying the Dockerfile and scripts there is no easy way to conditionally include/enable avahi and dbus that i could see. 

Since it seems my remote vps setup is the odd one out so i reduced the startup log noise and slightly reduced mem usage by adding the below to my compose file.

```
- "./empty:/etc/services.d/dbus/down"
- "./empty:/etc/services.d/avahi/down"
```

If you guys decide that these discovery services can't be made optional on build please just close this :+1:

**Comment by aptalca** [comment] 2016-11-02 13:16
After the container runs, you can shut off the avahi service with the following: `docker exec plex s6-svc -d /var/run/s6/services/avahi` (if avahi cannot start properly due to errors, use the `-O` option instead)

I actually had to implement it in a system.d service file (as ExecStartPost) where it waits for the avahi service to come up and then shuts it down, because the host already has avahi running and the container's avahi couldn't start, filling the logs with error messages.

**Comment by sparklyballs** [comment] 2016-11-03 10:57
i'm gonna close this, for setups like yours @thechile, you've already made your own solution.

Good for reference though in case it's needed for someone else in the same situation.

**Closed by sparklyballs** 2016-11-03 10:57 UTC
