### ISSUE TITLE
New (1.7.5.4035) Plex Server require UDEV to be installed

### ISSUE THREAD

**Issue by ctroncoso** [linuxserver/docker-plex#109] opened 2017-06-29 11:26 UTC
According to plex new features blog, the new update require udev to be installed. 

```
Unpacking plexmediaserver (1.7.5.4035-313f93718) over (1.7.3.3937-70f781325) ...
Setting up plexmediaserver (1.7.5.4035-313f93718) ...

##################################################################
#  NOTE: Your system does not have udev installed. Without udev  #
#        you won't be able to use DVBLogic's TVButler for DVR    #
#        or for LiveTV                                           #
#                                                                #
#        Please install udev and reinstall Plex Media Server to  #
#        to enable TV Butler support in Plex Media Server.       #
#                                                                #
#        To install udev run: sudo apt-get install udev          #
#                                                                #
##################################################################

Processing triggers for systemd (229-4ubuntu17) ...
```

**Comment by sparklyballs** [comment] 2017-07-01 11:01
at present it's not prudent for us to include udev as the installation routine fails when it is installed
and given that our docker updates the plex version on restart by default it would lead to mass breakages.
on the other hand if the issue is resolved in the next version of plex then it will be revisited. 
building plex's own docker from their git repository on my local dev box results in the same problem with the installer breaking when udev is installed.

**Closed by sparklyballs** 2017-07-01 11:01 UTC

**Comment by james-d-elliott** [comment] 2018-09-07 09:16
I think this may now be fixed. I've downgraded my plex via the console, installed udev, and had plex restart. It updated fine and no longer spits out the message. I only did this since I saw the warning when looking through logs and don't use PVR so can't test it.

**Comment by JRGonz** [comment] 2019-03-21 21:56
Noticed this in a smartos lx zone (which I’m guessing would be impossible to use udev with). I have a hdhomerun so a TVButler error really doesn’t affect me.
