### ISSUE TITLE
CPU usage stuck at 100%, server unresponsive

### ISSUE THREAD

**Issue by vascozorrinho** [linuxserver/docker-plex#248] opened 2020-11-25 20:24 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

After the update to the version 23.11.20, the container is using 100% of the CPU and it's unresponsive to the clients

------------------------------

## Expected Behavior
Low cpu usage and responsive server

## Current Behavior
CPU usage goes to 100% all the time and the server is unresponsive

## Steps to Reproduce
My instalation using DockSTARTer was updated with watchtower

## Environment
**OS:** Raspbian OS
**CPU architecture:** arm32
**How docker service was installed:** DockSTARTer default configs

## Docker logs
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    1000,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 40-chown-files: executing... ,
[cont-init.d] 40-chown-files: exited 0.,
[cont-init.d] 45-plex-claim: executing... ,
[cont-init.d] 45-plex-claim: exited 0.,
[cont-init.d] 50-gid-video: executing... ,
[cont-init.d] 50-gid-video: exited 0.,
[cont-init.d] 60-plex-update: executing... ,
Docker is used for versioning skip update check,
[cont-init.d] 60-plex-update: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Starting Plex Media Server.,
Error starting framework core for /usr/lib/plexmediaserver/Resources/Plug-ins-d87012962/OpenSubtitles.bundle.,
Error starting framework core for /usr/lib/plexmediaserver/Resources/Plug-ins-d87012962/LyricFind.bundle.,
Error starting framework core for /usr/lib/plexmediaserver/Resources/Plug-ins-d87012962/LocalMedia.bundle.,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    1000,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 40-chown-files: executing... ,
[cont-init.d] 40-chown-files: exited 0.,
[cont-init.d] 45-plex-claim: executing... ,
[cont-init.d] 45-plex-claim: exited 0.,
[cont-init.d] 50-gid-video: executing... ,
[cont-init.d] 50-gid-video: exited 0.,
[cont-init.d] 60-plex-update: executing... ,
Docker is used for versioning skip update check,
[cont-init.d] 60-plex-update: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Starting Plex Media Server.,
Error starting framework core for /usr/lib/plexmediaserver/Resources/Plug-ins-d87012962/MoviePosterDB.bundle.,
Error starting framework core for /usr/lib/plexmediaserver/Resources/Plug-ins-d87012962/PlexMovieNew.bundle.,
Error starting framework core for /usr/lib/plexmediaserver/Resources/Plug-ins-d87012962/LastFM.bundle.,

**Comment by robrechtme** [comment] 2020-11-25 20:27
+1
Same issue since latest release.

**Comment by karolisvitkus** [comment] 2020-11-25 21:05
+1
Same issue on Raspberry Pi4 (Raspbian OS arm32) after updating to this release.

**Comment by Roxedus** [comment] 2020-11-25 21:06
Dupe of #247

**Comment by tobinstultiens** [comment] 2020-11-25 21:31
+1 
Same issue had to manually reboot my Raspberry Pi twice.

**Comment by robrechtme** [comment] 2020-11-25 21:34
Changing the image tag from `latest` to `bionic` fixed it for me 🎉

**Comment by vascozorrinho** [comment] 2020-11-25 21:39
Same! but to be honest I still don't understand what's the difference between latest and bionic. what's better, more recent, and when/if i can go back to latest.

**Comment by jpmaior** [comment] 2020-11-26 12:12
I was able to narrow it down to a date problem. By running the date command, I got the following result.
![image](https://user-images.githubusercontent.com/51545390/100349141-42871800-2fe8-11eb-8dad-129988b79816.png)

**Comment by aptalca** [comment] 2020-11-26 12:21
The date issue is not the problem, it's a symptom. The issue and the solution are explained in the numerous issues in the plex and jellyfin repos

**Comment by yllekz** [comment] 2020-11-26 17:14
Also having this issue across multiple Raspberry Pi systems. CPU is pegged at 400% when this container is running. The problem started when I updated to the latest version.

**Comment by StanAngeloff** [comment] 2020-11-27 10:41
In https://github.com/linuxserver/docker-plex/issues/247#issuecomment-734007261 @Roxedus has outlined the cause. There's another fix which I opted in for:

```sh
# Enable the buster-backports repository
# See https://marksrpicluster.blogspot.com/2019/12/add-buster-backports-to-raspberry-pi.html
echo 'deb http://deb.debian.org/debian buster-backports main' | sudo tee /etc/apt/sources.list.d/buster-backports.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7638D0442B90D010
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
sudo apt update
# Install libseccomp2 from buster-backports. The package in the default repositories is version 2.3.3-4.
sudo apt install -t buster-backports libseccomp2
sudo reboot
```

This bumps `libseccomp2` to `2.4.4` which after a reboot resolved the issue for me.

**Comment by GazaShaggy** [comment] 2020-11-27 10:54
+1 on Pi4. Changed my stack to use this version instead "arm32v7-1.20.5.3600-47c0d9038-ls3"

**Comment by j0nnymoe** [comment] 2020-11-27 11:39
The fixes for this are here: https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal

**Closed by j0nnymoe** 2020-11-27 11:39 UTC
