### ISSUE TITLE
No access to WebGUI on Docker Rootless 

### ISSUE THREAD

**Issue by sw0ok** [linuxserver/docker-plex#327] opened 2022-08-20 04:15 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Upon accessing http(s)://192.168.1.89:32400/web WebGUI should appear. Server is using backedup config which uses relay to make server discoverable (CGNAT present) but app.plex.tv reports "SERVER UNAVAILABLE"
## Current Behavior

Response is "ERR_CONNECTION_REFUSED" instead.
## Steps to Reproduce

1. Install Docker Rootfull
2. Follow the guide [Run the Docker daemon as a non-root user (Rootless mode)](https://docs.docker.com/engine/security/rootless/)
3. Create container
4. Go to http(s)://192.168.1.89:32400/web
5. ERR_CONNECTION_REFUSED (UFW DISABLED)

## Environment
**OS: Debian GNU/Linux 11**
**CPU architecture:  KVM/QEMU (Standard PC (i440FX + PIIX, 1996) pc-i440fx-6.1)** x86_64 (Proxmox)
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

https://pastebin.com/e8fr5Px5

## Docker logs

https://pastebin.com/avajnXKs

Library is pulled from CIFS mounted SMB share running on VM with TrueNAS Core, which works properly when run rootfull, but what i noticed is that guidmap breaks some of the permissions on it 
`drwxr-xr-x 3 100999 100999 4096 Jul 21 08:30 Library`

with PUID/GUID=0 permissions are set to proper user/group.

**Comment by aptalca** [comment] 2022-08-20 04:39
Our images don't support rootless docker as our init processes often require root. Once the init steps are completed, most of our images drop privileges and run the apps as the PUID set.

In your case, you're running a limitation of rootless docker with host networking

**Comment by aptalca** [comment] 2022-08-20 04:40
Closing as it's not a bug with our image and you seem to be on our discord server already

**Closed by aptalca** 2022-08-20 04:40 UTC

**Comment by sw0ok** [comment] 2022-08-20 05:55
You actually made me tinker further and it finally works, solution was the bridge networking by publishing ports specified in your docs, so now docker run looks like this https://pastebin.com/CL81M2Lr

I see now that host networking is not supported in rootless mode as of Docker 19.03 as per this post I've found [ServerFault.com](https://serverfault.com/questions/1019889/how-to-bind-a-port-in-a-host-network-mode-from-a-container-run-by-a-rootless-d) as far as I understand is because they're in different namespaces that Rootles daemon doesn't have access to (?). So what are the drawbacks of bridge mode in this scenario? First would be first time setup requiring claim_token to be provided, and further down the road additional step in case of providing remote access to PMS [would this setup tie me to relay completely?](?), is that about right, is there anything else I should be aware of?
