### ISSUE TITLE
Plex Media Server Crash - system_error: clock_gettime(CLOCK_MONOTONIC) failed

### ISSUE THREAD

**Issue by Rubl80** [linuxserver/docker-plex#270] opened 2021-05-26 05:56 UTC
After the most recent bionic update my Plex won't start and is crashing according to the logs.

It states the following reason in the log:
------------------------------------------
_****** PLEX MEDIA SERVER CRASHED, CRASH REPORT WRITTEN: /config/Library/Application Support/Plex Media Server/Crash Reports/1.23.1.4571-6119e8eed/PLEX MEDIA SERVER/ae788eb7-4ba9-4883-5b125980-b05d8bbc.dmp

Starting Plex Media Server.

libc++abi: terminating with uncaught exception of type std::__2::system_error: clock_gettime(CLOCK_MONOTONIC) failed: Operation not permitted

libc++abi: terminating with uncaught exception of type std::__2::system_error: clock_gettime(CLOCK_MONOTONIC) failed: Operation not permitted_
------------------------------------------
Anybody else have the same experience, and perhaps now a way to fix it?
I have tried to remove and reinstall the container, but did not work.

I am running my Plex Server on a Raspberry Pi 4 with OpenMediaVault 5

**Comment by Roxedus** [comment] 2021-05-26 06:02
Please provide *full* logs, including the banner

**Comment by Rubl80** [comment] 2021-05-26 06:23
[_plex_logs.txt](https://github.com/linuxserver/docker-plex/files/6544236/_plex_logs.txt)

Here is the log from the container.. 

I also tried to retrieve the crash report log from Plex in the container. But it keeps on deleting the file, before I have a chance to copy or open it up.

**Comment by Roxedus** [comment] 2021-05-26 06:38
Those are not the container logs.

**Comment by Rubl80** [comment] 2021-05-26 11:23
[json.txt](https://github.com/linuxserver/docker-plex/files/6546286/json.txt)

Is this the right one?

**Comment by Roxedus** [comment] 2021-05-26 11:25
It is, now you are missing all the other info we ask for in the issue template

**Comment by Rubl80** [comment] 2021-05-26 12:25
Think I got it all now :)

https://github.com/linuxserver/docker-plex
https://github.com/linuxserver/docker-plex

------------------------------

## Expected Behavior
After updating my container to version 1.23.1.4571-6119e8eed-ls50 (bionic), the Plex Media Server will not start. Normally it works, and it was working yesterday.

## Current Behavior
The Plex Media Server is nowcrashing as stated in the log files. It started to happen after the latest update.

## Steps to Reproduce
1. I have tried several time to run the Stack, and the same error occur each time.

## Environment
OpenMediaVault 5.6.7.1
**CPU architecture:** arm32 (Raspberry Pi 4 8GB)
**How docker service was installed:** In Portainer as a Stack by using: ghcr.io/linuxserver/plex:bionic

## Command used to create docker container (run/create/compose/screenshot)
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex:bionic
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK=022
    volumes:
      - /home/plex/config/:/config
      - /srv/myfilename/Plex/Movies:/Movies
    restart: unless-stopped

## Docker logs
Attached in previous post

**Comment by JoeBoJoe** [comment] 2021-05-26 14:32
I'm having the same issue running on my raspberry pi 3B.

**Comment by DFlexy** [comment] 2021-05-26 14:59
For me too stop WORK version BIONIC RASPI4
Cant open web more 

root@Rasphouse:/home/pi# ping plex
PING plex.lan (172.20.0.5) 56(84) bytes of data.
64 bytes from plex.lan (172.20.0.5): icmp_seq=1 ttl=64 time=0.422 ms
64 bytes from plex.lan (172.20.0.5): icmp_seq=2 ttl=64 time=0.098 ms
64 bytes from plex.lan (172.20.0.5): icmp_seq=3 ttl=64 time=0.098 ms
64 bytes from plex.lan (172.20.0.5): icmp_seq=4 ttl=64 time=0.069 ms
64 bytes from plex.lan (172.20.0.5): icmp_seq=5 ttl=64 time=0.112 ms

docker run -d \
  --name=plex \
  --hostname plex \
  --dns=10.10.10.254 \
  -p 32400:32400/tcp \
  -p 3005:3005/tcp \
  -p 8324:8324/tcp \
  -p 32469:32469/tcp \
  -p 1900:1900/udp \
  -p 32410:32410/udp \
  -p 32412:32412/udp \
  -p 32413:32413/udp \
  -p 32414:32414/udp \
  -e TZ=America/Sao_Paulo \
  -e PUID=1000 \
  -e PGID=1000 \
  -e VERSION=docker \
  -v plex:/config \
  -v /media/:/media \
  --network=lan \
  --ip=172.20.0.5 \
  --restart unless-stopped \
  linuxserver/plex:bionic

**Comment by JoeBoJoe** [comment] 2021-05-26 15:03
As a temporary workaround, you could create a new docker with the same config but with the docker image version tag which was last working for you. For me that happens to be "bionic-1.22.3.4523-d0ce30438-ls31" which I can confirm is working right now.

**Comment by DFlexy** [comment] 2021-05-26 15:07
i back for linuxserver/plex:bionic-1.22.3.4523-d0ce30438-ls30
work now

**Comment by Rubl80** [comment] 2021-05-26 15:07
Thanks @JoeBoJoe your workaround is working..

**Comment by j0nnymoe** [comment] 2021-05-26 15:23
I would highly recommend moving away from the bionic release and moving to `:latest`.

**Comment by JoeBoJoe** [comment] 2021-05-26 15:33
> I would highly recommend moving away from the bionic release and moving to `:latest`.

For me that would require a OS update which I have been putting off for some time. [https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal](url)

That's also the main reason I moved from latest to bionic.

**Comment by JoeBoJoe** [comment] 2021-05-26 15:38
> > > I would highly recommend moving away from the bionic release and moving to `:latest`.
> > 
> > 
> > For me that would require a OS update which I have been putting off for some time. [https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal](url)
> > That's also the main reason I moved from latest to bionic.
> 
> Yep I figured as much. This is only ever a band aid fix and we don't plan support it long term.
> You shouldn't need to do an OS upgrade, just install the backported packages + make sure you're running the latest container.

I attempted option 2 & 3 however wasn't able to get it working and couldn't spare the time to look into it further.
Are you saying the following quote from the article is no longer accurate?

 "At the time of writing we currently offer a bionic tag for Plex and Jellyfin that will receive the same care as latest for the foreseeable future."

**Comment by j0nnymoe** [comment] 2021-05-26 15:40
> Are you saying the following quote from the article is no longer accurate?

Pass - I hadn't realised that comment was on there, but if you're using any other of containers and update them, you're going to hit the same issue and we don't provide bionic tags for those.

**Comment by Roxedus** [comment] 2021-05-26 15:45
Said future is due to end

**Comment by JoeBoJoe** [comment] 2021-05-26 15:49
> Said future is due to end

[Soon to be me.](https://www.youtube.com/watch?v=MDl4W3_6dqA)

**Comment by smvb64** [comment] 2021-05-26 16:27
I having the eaxct same issue on my end - Ill give latest a try again but worst case I can use the last working image

**Comment by j0nnymoe** [comment] 2021-05-26 16:40
> I having the eaxct same issue on my end - Ill give latest a try again but worst case I can use the last working image

You need to update your libseccomp for latest to be working for you.

**Comment by EbenezumCZ** [comment] 2021-05-26 16:42
I can also confirm this issue.
Working workaround - fallback to -> linuxserver/plex:bionic-1.22.3.4523-d0ce30438-ls30

RPi3B+ , latest official raspios Buster , Portainer 2.5

**Comment by smvb64** [comment] 2021-05-26 16:45
> 
> 
> > I having the eaxct same issue on my end - Ill give latest a try again but worst case I can use the last working image
> 
> You need to update your libseccomp for latest to be working for you.

> Thank you, Ill look until it- I never did that before. Ill see if I can find a guide

> 
> 
> I can also confirm this issue.
> Working workaround - fallback to -> linuxserver/plex:bionic-1.22.3.4523-d0ce30438-ls30
> 
> RPi3B+ , latest official raspios Buster , Portainer 2.5

> Yup working for me right now too

**Comment by EbenezumCZ** [comment] 2021-05-26 16:52
> 
> 
> > > I having the eaxct same issue on my end - Ill give latest a try again but worst case I can use the last working image
> > 
> > 
> > You need to update your libseccomp for latest to be working for you.
> 
> Thank you, Ill look until it- I never did that before. Ill see if I can find a guide
> 
> > I can also confirm this issue.
> > Working workaround - fallback to -> linuxserver/plex:bionic-1.22.3.4523-d0ce30438-ls30
> > RPi3B+ , latest official raspios Buster , Portainer 2.5
> 
> Yup working for me right now too

I guess this might help - backports for Debian Buster  - https://docs.linuxserver.io/faq#option-3
Unfortuntely I cannot test it right now.

**Comment by insickin** [comment] 2021-05-26 20:47
> I guess this might help - backports for Debian Buster - https://docs.linuxserver.io/faq#option-3
> Unfortuntely I cannot test it right now.

I can confirm that this works

**Comment by Rubl80** [comment] 2021-05-27 05:18
> > I guess this might help - backports for Debian Buster - https://docs.linuxserver.io/faq#option-3
> > Unfortuntely I cannot test it right now.
> 
> I can confirm that this works

Option 3 also working for me, and now back to using :latest.

**Comment by Andrewb967** [comment] 2021-06-03 06:14
I'm trying to install it for the first time and I have had no luck because of the error message. :(

**Comment by j0nnymoe** [comment] 2021-06-03 07:06
@Andrewb967 if you're having problems using this container, you need to fix your host with the latest version of libseccomp2 (and docker) like many users have above.

**Closed** 2021-06-03 13:48 UTC

**Comment by JoeBoJoe** [comment] 2021-06-03 15:11
> @Andrewb967 if you're having problems using this container, you need to fix your host with the latest version of libseccomp2 (and docker) like many users have above.

I believe the reason this is not possible for me is that I am still using a distro based on DebianStretch and so it sounds like updating OS is the only solution from what I understand under Option 4 of the faq.

**Comment by mcgyver83** [comment] 2021-06-04 07:56
Option 2 worked for me [FAQ](https://docs.linuxserver.io/faq#option-2)
I'm on Raspberry Pi2 with OpenMediaVault 5

**Comment by Andrewb967** [comment] 2021-06-04 16:03
Thanks for the quick replies. I finally figured out the issue. It was a ID10T-U53R error lol. Thanks again.

**Comment by chrisallen** [comment] 2021-08-05 11:13
I believe that adding `export SYSCALL_MAX_ENABLED=1` should fix this issue. It was required only on Synology platforms with our new builds. (something to do with the kernel modifications they have)
