### ISSUE TITLE
Can't user plex over Web browser

### ISSUE THREAD

**Issue by mlinko6** [linuxserver/docker-plex#405] opened 2024-09-13 05:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Yesterday all was working just fine, but today I just get errors playing videos over chrome:

Error code: h3 (Decode) - if I user the option in Debug Setting: Use alternate streaming protocol for video playback
Error code: s3015 (Media)

It is working over Android TV but I have a problem starting a video over the Browser - Chrome in my case. It is working if I use Mozilla which is very Strange...

The error ONLY happens if I wake the Laptop up from "sleepmode" but I'm doing it all the time and it never happened until now.

### Steps To Reproduce

Yesterday all was working just fine, but today I just get errors playing videos over chrome:

Error code: h3 (Decode) - if I user the option in Debug Setting: Use alternate streaming protocol for video playback
Error code: s3015 (Media)

It is working over Android TV but I have a problem starting a video over the Browser - Chrome in my case. It is working if I use Mozilla which is very Strange...

### Environment

```markdown
- OS: Synology
- How docker service was installed: Portainer - Running on Synology Docker Platform
```

### CPU architecture

x86-64

### Docker creation

```bash
How docker service was installed: Portainer - Running on Synology Docker Platform
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1026
User GID:    100
───────────────────────────────────────
Linuxserver.io version: 1.41.0.8992-8463ad060-ls235
Build-date: 2024-09-12T11:27:40+00:00
───────────────────────────────────────
    
**** Server already claimed ****
**** adding /dev/dri/card0 to video group root with id 0 ****
**** The device /dev/dri/card0 does not have group read/write permissions, attempting to fix inside the container. ****
**** creating video group video52wc with id 937 ****
**** adding /dev/dri/renderD128 to video group video52wc with id 937 ****
No update required
[custom-init] No custom files found, skipping...
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Connection to localhost (::1) 32400 port [tcp/*] succeeded!
[ls.io-init] done.
Critical: libusb_init failed
Connection to 172.104.139.30 closed by remote host.
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1026
User GID:    100
───────────────────────────────────────
Linuxserver.io version: 1.41.0.8992-8463ad060-ls235
Build-date: 2024-09-12T11:27:40+00:00
───────────────────────────────────────
    
**** Server already claimed ****
**** The device /dev/dri/card0 does not have group read/write permissions, attempting to fix inside the container. ****
**** permissions for /dev/dri/renderD128 are good ****
No update required
[custom-init] No custom files found, skipping...
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Connection to localhost (::1) 32400 port [tcp/*] succeeded!
[ls.io-init] done.
Critical: libusb_init failed
```

**Comment by drizuid** [comment] 2024-10-15 13:04
A couple things
1) we do not support or recommend using portainer to deploy containers
2) we do not support or recommend using the synology docker ui to deploy containers
3) if it works on other clients and other browsers, this doesn't sound like a container issue. We support the container, not the application. I would suggest reaching out to plex about this and ensuring this isn't some addon issue with your chrome instance.

With that said, I will close this as it's out of scope for our support and I cannot reproduce the issue in chrome, chromium, edge, or firefox.

**Closed by drizuid** 2024-10-15 13:04 UTC
Labels: no-issue-activity
