### ISSUE TITLE
Hangs while executing 10_add_user_abc.sh

### ISSUE THREAD

**Issue by rossdargan** [linuxserver/docker-plex#45] opened 2016-07-04 22:20 UTC
No idea why, but after running the container I'll often find that it has hung on this script for some reason (I'm running it on ubuntu):

ross@dar-docker-01:~$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Not really sure what else I can do to try and track down why it hangs, and a restart of the container always fixes it.

**Comment by mattberther** [comment] 2016-07-15 02:07
I see the same thing when running on my synology nas:

```
~ @ synology (matt) $ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.4.2
 Git commit:   eabacaa-synology
 Built:        Sat Jun 18 19:01:00 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.4.2
 Git commit:   eabacaa-synology
 Built:        Sat Jun 18 19:01:00 2016
 OS/Arch:      linux/amd64
```

**Comment by rahuljawale** [comment] 2016-07-17 02:49
I see this issue too.

**Comment by j0nnymoe** [comment] 2016-07-17 17:36
Could we get some docker logs of this happening and we can look into this further :)

**Comment by rossdargan** [comment] 2016-07-17 19:14
I'll get the logs the next time I bounce it, but there are only two lines, and the subject is the last line on it!

**Comment by mattberther** [comment] 2016-07-17 19:17
Thanks @j0nnymoe. This is definitely a weird issue. I never see this on my Mac. But I *always* see it on the synology.

```
htpc @ synology (matt) $ docker-compose logs plex
Attaching to htpc_plex_1
plex_1         | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
plex_1         | *** Running /etc/my_init.d/10_add_user_abc.sh...
```

After `docker-compose restart plex`, I see this:

```
htpc @ synology (matt) $ docker-compose restart plex
Restarting htpc_plex_1 ... done
htpc @ synology (matt) $ docker-compose logs plex
Attaching to htpc_plex_1
plex_1         | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
plex_1         | *** Running /etc/my_init.d/10_add_user_abc.sh...
plex_1         | *** An error occurred. Aborting.
plex_1         | *** Shutting down /etc/my_init.d/10_add_user_abc.sh (PID 6)...
plex_1         | *** Init system aborted.
plex_1         | *** Killing all processes...
plex_1         | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
plex_1         | *** Running /etc/my_init.d/10_add_user_abc.sh...
plex_1         | 
plex_1         | -------------------------------------
plex_1         |           _     _ _
plex_1         |          | |___| (_) ___
plex_1         |          | / __| | |/ _ \ 
plex_1         |          | \__ \ | | (_) |
plex_1         |          |_|___/ |_|\___/
plex_1         |                |_|
plex_1         | 
plex_1         | Brought to you by linuxserver.io
plex_1         | We do accept donations at:
plex_1         | https://www.linuxserver.io/donations
plex_1         | -------------------------------------
plex_1         | GID/UID
plex_1         | -------------------------------------
```

and the container starts as normal.

The section of my docker-compose file is this (although it doesnt matter if i run via compose or not):

```
  plex:
    image: linuxserver/plex
    networks:
      - internal
    env_file:
      - ./htpc.env
    environment:
      VERSION: 'latest'
    volumes:
      - ./plex:/config
      - /volume1/media:/data
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
```

**Comment by rahuljawale** [comment] 2016-07-20 06:25
I see that it's waiting at step:

```
           ├─5272 /bin/bash /etc/my_init.d/10_add_user_abc.sh
           └─5274 usermod -o -u 999 abc
```

Does it have anything to do with huge library? My Plex metadata directory size is around 7 GB

**Comment by mattberther** [comment] 2016-07-20 21:47
I don't think it has to do with size. That should only come into play when it does the chown -- which is in a later script. The chown also only happens once as its guarded by a check for linuxserver.lock file. Again, if I restart the container immediately it works fine.

**Comment by inercia** [comment] 2016-08-18 23:05
I see the `usermod` is hanging. The scripts continue after killing `usermod`, but other things break later on...

**Comment by lonix** [comment] 2016-08-22 08:07
There might be a issue with the user context synology is exectuting docker, e.g. ( the user running docker it self might not be allowed to do a usermod). But ill let the Linuxserver io team handle this one, just my two cents.

**Comment by mattberther** [comment] 2016-08-22 13:45
@lonix i wondered about this too - but am not sure why everything works when you restart the container.

**Comment by rossdargan** [comment] 2016-08-22 14:03
I'm running it under Ubuntu so not sure it's that.

**Comment by blackbarn** [comment] 2016-08-30 14:45
This also happens to me, running ubuntu 16. Has been for quite some time. I have to manually execute the script and then restart the container:

```bash
docker exec -it plex /etc/cont-init.d/10-adduser;
docker restart plex;
```

Otherwise it just hangs when it tries to execute 10-adduser on its own.

**Comment by j0nnymoe** [comment] 2016-08-31 08:49
This image was recently updated, please could you try pulling the latest image and see you suffer from the same issue. The update is a drop-in replacement but please backup your appdata first.

**Comment by rossdargan** [comment] 2016-08-31 13:14
Still no luck - here are the logs:

ross@dar-docker-01:/mnt/docker$ docker logs plex
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
ross@dar-docker-01:/mnt/docker$ docker restart plex
plex
ross@dar-docker-01:/mnt/docker$ docker logs plex
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
...

**Comment by sparklyballs** [comment] 2016-08-31 13:40
@rossdargan 

can you try something for me please ?

start the container...

exec in with 

`docker exec -it plex bash`

and run the following

`apt-get update && apt-get install -y nano`

`nano -c /etc/cont-init.d/10-adduser`

and remove or comment the last 3 lines

`chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults`

exit out and restart the container a few times, see if it solves the issue.

**Comment by rossdargan** [comment] 2016-08-31 13:48
I restarted 6 or 7 times after making that change and it was fine.

**Comment by sparklyballs** [comment] 2016-08-31 14:03
ok, thanks.

it's very odd that not seeing it in any other images and only a few people with this one.

**Comment by mattberther** [comment] 2016-08-31 15:33
@sparklyballs the problem for me is not on restart -- its on the initial start *only*.

**Comment by rjorgenson** [comment] 2016-08-31 15:47
@mattberther @sparklyballs me as well. After the initial build it will hang here, if I kill and restart it there are no issues.

**Comment by sparklyballs** [comment] 2016-08-31 16:03
i have to look at the implications of removing the line for the container as a whole though.
for instance permissions on the root folder could be askew on some systems.
could break even more by fixing something.

**Comment by rjorgenson** [comment] 2016-08-31 16:13
For what it's worth, this only happens if I mount my /config directory externally, if I run it with an internal /config it starts up no problem. While it's stuck on 10-adduser I ran a shell to it and checked, the /config is set to abc:users(with my external PUID/PGID) and the /app and /defaults are still owned by root, top shows the usermod command as running using up a fair bit of cpu(15%) .. been going for about 5 minutes now. It seems like the usermod command changes the UID of abc, and then never closes out. Once I restart the container it sees that the UID is correct and skips that part.

**Comment by patsissons** [comment] 2016-10-12 04:06
I can confirm @rjorgenson's findings. `usermod` command is still running but if you check `id -u abc` you see that it is updated with `PUID`.

**Comment by sparklyballs** [comment] 2016-11-20 12:06
made a change to the add user script universally **hopefully** may resolve this issue.

going to close this, if issue is still present then suggest users open new issue.

**Closed by sparklyballs** 2016-11-20 12:06 UTC

**Comment by patsissons** [comment] 2016-11-20 19:48
sounds good, i'll post my results once on the next plex update.

**Comment by mattberther** [comment] 2016-11-21 02:13
I grabbed latest version and didnt see any difference.

**Comment by patsissons** [comment] 2016-12-04 20:55
confirmed, still the same issue.

**Comment by LukeAbell** [comment] 2016-12-07 08:00
Same issue here after latest update.

**Comment by Artiume** [comment] 2019-02-22 01:05
I'm having this issue happen to me on an odroid hc-2 running Ubuntu 18.04.2 LTS (4.14.94-155   armv7l)

Docker version 18.09.2 (swarm mode)

docker logs:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,

It will hang on this script which lead me to this ticket. 
removing env var - PUID: 1000 allows the container to successfully build. 

I was able to verify that the removal of 

chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults

did allow the container to successfully build.

A side note; due to the deployment nature of swarm mode, this merely just caused the container to be moved to the status of 'completed' and the service running the container management will spin up a new container, which recreates the 10-adduser file.
