### ISSUE TITLE
New build (1.21) - lost connection to PMS

### ISSUE THREAD

**Issue by Ubergeeksov** [linuxserver/docker-plex#251] opened 2020-12-02 09:49 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

see: https://forums.plex.tv/t/cannot-find-server/656438

------------------------------

## Expected Behavior
I should be able to contact the PMS

## Current Behavior
I am unable to access the PMS
I was still able to use iOS and SmartTV to view content.
Library was not being updated
Appears to have started at time of new release (1.21)

## Steps to Reproduce
1.Attempting to access WebUI via port 32400 - libraries not available
2.Deleted container and config files before reinstalling
3.Now have message at server setup "A problem has been detected with a core component of PMS"
4.

## Environment
**OS: OMV5**
**CPU architecture:** ARM v7 processor - armhf
**How docker service was installed:**
Portainer: linuxserver/plex:latest

## Command used to create docker container (run/create/compose/screenshot)
Portainer

**Comment by Roxedus** [comment] 2020-12-02 10:34
Dupe of #247

**Closed** 2020-12-02 10:47 UTC
