### ISSUE TITLE
Private Ip issue with Rancher setup

### ISSUE THREAD

**Issue by Noext** [linuxserver/docker-plex#239] opened 2020-10-31 13:14 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I have currently setup this docker image in my local Rancher env ( LAN network 192.168.1.x )  behind a rancher loadbalancer ( haproxy )

with a browser i can go to 192.168.1.Y:32400  and use plex with no issue at all but with the plex app i can only use the relay server , i'm unable to use a lan access to the server

i think that the problem is that plex has register my local docker ip for the "private ip" setting in the remote access

screenshot of the remote access : [https://i.imgur.com/l1YpiLw.png](url)

------------------------------

## Expected Behavior

LAN acecss should be working

## Current Behavior

LAN access is not working in the plex app ( and only the plex app )

## Steps to Reproduce

1. Install Rancher OS 1.6
2. Create a stack with this image and a loadbalancer 
3. navigate to the LAN ip of the rancher host machine and the plex port, it is working
4. open plex app, server is found but only play video via internet and not LAN

## Environment
**OS:** debian 10
**CPU architecture:** x86_64
**How docker service was installed:** simple install from docker official tutorial , same for rancher

## Command used to create docker container (run/create/compose/screenshot)

docker compose from rancher export
`version: '2'
services:
  Loadbalancer:
    image: rancher/lb-service-haproxy:v0.9.14
    expose:
    - 32400:32400/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      web.https: 'true'
  Plex:
    image: linuxserver/plex
    environment:
      PUID: '1000'
      VERSION: docker
      PGID: '1000'
      PLEX_CLAIM: claim-GRXsY6QU1LDbofbT6jV-
    stdin_open: true
    volumes:
    - /mnt/NOEXT-NAS/Video:/video
    - /opt/project-data/plex:/config
    tty: true
    ports:
    - 32400:32400/tcp
    labels:
      io.rancher.container.pull_image: always
`

**Comment by tobbenb** [comment] 2020-10-31 13:31
Why have you set the port manually to 443?
You also have an option in plex to set the IP range that are treated as local.
I don't know what haproxy is and we don't support it, so if it's working without haproxy, that is as far as our support goes.

GitHub is reserved for bugs and support issues should be done on discord or our discourse forum.

**Comment by Noext** [comment] 2020-10-31 15:28
haproxy act as a reverse proxy, plex is mapped to 443 because its haproxy that redirect to the 9091 port 

before using rancher and haproxy i used  apache acting as reverse proxy with no problem, so i dont think haproxy is causing the issue here

**Comment by aptalca** [comment] 2020-10-31 15:48
?? What 9091 port?

Either port forward 443:32400 directly on your router/firewall (not reverse proxy) and set that external port var in plex gui, or reverse proxy and follow these instructions: https://github.com/linuxserver/reverse-proxy-confs/blob/master/plex.subdomain.conf.sample#L5 and also set the LAN networks on the same page for local access.

You're trying to use a reverse proxy where plex is trying to connect directly.

In any case, closing because it's not a bug. Feel free to drop by our forums or discord to discuss.

**Closed by aptalca** 2020-10-31 15:48 UTC

**Comment by Noext** [comment] 2020-10-31 18:00
Sorry i mean 443:32400 not 9091 ( i was looking at the transmission configuration at the same time )

i think that the problem here , is that plex in docker register as private ip the ip of docker (10.x.x.x ) so it cannot be detected on other network like 192.x.x.x

**Comment by tobbenb** [comment] 2020-11-01 22:43
Please use discord or discourse for support as already said. And you can set the IP range that is considered local in the plex settings, as I have said to you earlier.
